# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SD Girls Coding Camp
email: ksansev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The San Diego Girls Coding Camp aims to introduce girls to Computer Science
    and programming.
baseurl: "{{site.github.url}}" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  sd-girls-coding-camp

# Build settings
markdown: kramdown
